import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./component/upload/storeProvider";
import SessionWrapper from "@/utils/SessionWrapper";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html >
      <body className={inter.className}>
        <StoreProvider>
          <SessionWrapper>
            {children}
          </SessionWrapper>
        </StoreProvider>
      </body>
    </html>
  );
}
