import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./component/upload/storeProvider";
import SessionWrapper from "@/utils/SessionWrapper";
import Nav from "./component/header/nav";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <StoreProvider>
          <SessionWrapper>
            <Nav />
            <div className="bg-[url('/font.webp')] bg-center bg-cover">
              {children}
            </div>
          </SessionWrapper>
        </StoreProvider>
      </body>
    </html>
  );
}
